export default {
  name: 'ApproveChainLine',
  primaryKey: 'approveChainLineId',
  autoQuery: false,
  paging: false,
  fields: [
    { name: 'approveChainLineId', type: 'number' },
    { name: 'approveChainId', type: 'number' },
    { name: 'name', type: 'string', label: '名称', required: true, unique: true },
    { name: 'description', type: 'string', label: '描述' },
    { name: 'approveType', type: 'string', label: '' },
    { name: 'assignee', type: 'string', label: '审批人', lookupCode: 'wfl.ASSIGNEE' },
    { name: 'assignGroupObject', type: 'object', label: '审批岗位', lovCode: 'WFL_POSITION_LOV', textField: 'name' },
    { name: 'assignGroup', type: 'string', label: '审批岗位', lovCode: 'WFL_POSITION_LOV', textField: 'positionCode', valueField: 'positionCode' },
    { name: 'assignGroupName', type: 'string', label: '审批岗位', bind: 'assignGroup.name' },
    { name: 'formKey', type: 'string', label: '表单' },
    { name: 'sequence', type: 'number', label: '顺序号', step: 1, defaultValue: 10 },
    { name: 'skipExpression', type: 'string', label: '跳过条件' },
    { name: 'breakOnSkip', type: 'boolean', label: '跳过时终止', falseValue: 'N', trueValue: 'Y' },
    { name: 'enableFlag', type: 'boolean', label: '启用', defaultValue: 'Y', falseValue: 'N', trueValue: 'Y' },
    { name: 'processKey', type: 'string' },
    { name: 'usertaskId', type: 'string' },
  ],
};
