export default {
  autoQuery: true,
  pageSize: 20,
  selection: false,
  dataKey: 'data',
  queryUrl: '/wfl/query/process-instances/monitor',
  fields: [
    { name: 'id', type: 'string', label: '流程ID' },
    { name: 'processName', type: 'string', label: '流程名称' },
    { name: 'taskName', type: 'string', label: '当前节点' },
    { name: 'startUserName', type: 'string', label: '申请人姓名' },
    { name: 'startUserId', type: 'string', label: '申请人' },
    { name: 'currentApprover', type: 'string', label: '当前处理人' },
    { name: 'startTime', type: 'string', label: '创建时间' },
    { name: 'endTime', type: 'string', label: '结束时间' },
    { name: 'state', type: 'string', label: '流程状态' },
    { name: 'suspended', type: 'boolean' },
  ],
  queryFields: [
    { name: 'processInstanceId', type: 'string', label: '流程ID' },
    { name: 'processDefinitionNameLike', type: 'string', label: '流程名称' },
    { name: 'startUserName', type: 'string', label: '申请人' },
    { name: 'startedAfter', type: 'date', label: '创建日期从' },
    { name: 'startedBefore', type: 'date', label: '创建日期到' },
    { name: 'taskState', type: 'string', label: '流程状态', lookupCode: 'wfl.MANAGER_STATE', defaultValue: 'all' },
    { name: 'finishedAfter', type: 'date', label: '结束日期从' },
    { name: 'finishedBefore', type: 'date', label: '结束日期到' },
  ],
};
